version: '3.8'
services:
  postgres:
    image: postgres:15.3
    container_name: postgres-container
    restart: always
    environment:
      POSTGRES_USER: derian
      POSTGRES_PASSWORD: 7474
      POSTGRES_DB: home_depot
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
